Repository UniAuth/http-exception-transformer, pull requests merged in 2021-03, with the labels that each got.

#5 added error code till 410
  src/lib/source.ts
Labels: gssoc21, level4

#10 feat(CI): add github action that tests and builds the package
  .github/workflows/main.yml
Labels: gssoc21, level3

#11 fix wrong status codes being sent
  package.json
  src/lib/exceptions/ConflictException.gen.ts
  src/lib/exceptions/ForbiddenException.gen.ts
  src/lib/exceptions/GoneException.gen.ts
  src/lib/exceptions/MethodNotAllowedException.gen.ts
  src/lib/exceptions/NotAcceptableException.gen.ts
  src/lib/exceptions/ProxyAuthenticationException.gen.ts
  src/lib/exceptions/RequestTimeOutException.gen.ts
  src/lib/exceptions/index.ts
  src/lib/index.ts
  src/lib/source.ts
Labels: enhancement
